trigger:
- '*'

variables:
  group: 'appcfg'
  buildConfiguration: 'Release'  
stages:
- stage: 'Deploy'
  displayName: 'Deploy the web application'
 
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
         
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Maelo''s Subscription - No tocar (ad7245e9-fcaa-4b37-a5c3-8ae951cc4bbc)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                appname=""$(pjname)"-app"
                rgname=""$(pjname)"-rg"
                echo "$appname"
                echo "$rgname"
                az login --service-principal --username 9062c44e-7db5-414c-9bfc-4126c88cacd2 --password pjAshf8HWYXFfx.kC.dWWJIb0PWn8CB0IS --tenant 9acf6dd6-1978-4d9c-9a9c-c9be95245565 & 
                az account set --subscription "ad7245e9-fcaa-4b37-a5c3-8ae951cc4bbc"
                if az group show -n "$rgname" -o none; then
                echo "RG is Already created"
                else 
                echo "Creating" &
                az group create -n "$rgname" --location eastus &
                az webapp create -g "$appname" -p /subscriptions/ad7245e9-fcaa-4b37-a5c3-8ae951cc4bbc/resourceGroups/DevOpsPractices-rg/providers/Microsoft.Web/serverfarms/devopslab_linux -n mytest5637-app --runtime "DOTNETCORE|3.1" &
                fi
              useGlobalConfig: true
   